
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 14 17:03:36 CET 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 48;
  public static final int MAP = 18;
  public static final int LBRACKET = 38;
  public static final int CONST = 6;
  public static final int NOT_EQUAL = 26;
  public static final int LOWER = 44;
  public static final int GREATER = 42;
  public static final int LPAREN = 36;
  public static final int CONTINUE = 14;
  public static final int NUM_CONST = 47;
  public static final int INTERFACE = 19;
  public static final int MINUS = 21;
  public static final int RPAREN = 37;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int CLASS = 4;
  public static final int INC = 30;
  public static final int DIV = 23;
  public static final int PLUS = 20;
  public static final int IF = 7;
  public static final int THIS = 46;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 39;
  public static final int EQUALS_TO = 25;
  public static final int EQUAL = 29;
  public static final int GREATER_EQUAL = 43;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 22;
  public static final int COMA = 34;
  public static final int SEMI_COLON = 32;
  public static final int MOD = 24;
  public static final int IDENT = 50;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int COLON = 33;
  public static final int UNION = 15;
  public static final int LBRACE = 40;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int WHILE = 17;
  public static final int RBRACE = 41;
  public static final int LOWER_EQUAL = 45;
  public static final int EXTENDS = 13;
  public static final int BOOL_CONST = 49;
  public static final int DEC = 31;
  public static final int PRINT = 9;
  public static final int DO = 16;
}

